name: AvarastGameManager
version: '1.0'
main: io.github.TitouxJr.avarastGameManager.AvarastGameManager
api-version: '1.20'
description: Un plugin de mini-jeu pour les serveurs Minecraft
commands:
  extraction:
    description: Démarrer ou arrêter le mini-jeu Extraction
    usage: "§cUtilisation : /<command> <start|stop>"
    permission: avarastgamemanager.extraction
permissions:
  avarastgamemanager.extraction:
    description: Permet aux joueurs de démarrer et d'arrêter le mini-jeu extraction
    default: true
