name: AvarastGameManager
version: '0.1-1.20.1'
main: io.github.TitouxJr.avarastGameManager.AvarastGameManager
api-version: '1.20'
authors: [ Titoux ]
description: The GameManager Plugin for Avarast Server
