name: AvarastGameManager
version: '1.0'
main: io.github.TitouxJr.avarastGameManager.AvarastGameManager
api-version: '1.20'
description: A mini-game manager plugin for Minecraft servers
commands:
  extraction:
    description: Start or stop the Extraction mini-game
    usage: /<command> [stop]
    permission: avarastgamemanager.extraction
permissions:
  avarastgamemanager.extraction:
    description: Allows players to start and stop the extraction mini-game
    default: true
